title: "Sally Anthony Taylor"
author: "Sally Anthony Taylor Family"
description: ""
more: "read more »"
url: "https://www.sallyanthonytaylor.com/"
baseurl: "/"
# paginate: 2
permalink: pretty
excerpt_separator: "\n\n\n" # two blank lines

style:
  minimalist: true
  dark: false

navigation:
  - index.md
  - obituary.md
  - share-memories.md
  - online-visitations.md
  - memorial-service.md
  - sally-through-81-years.md
  - memorial-gifts.md

comments:
#  disqus: "disqus-contrast"
#  isso: "comments.mysite.org"

links: # see http://fontawesome.io/icons/#brand for all possible icons
  # - envelope: "mailto:"

defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
sass: {style: expanded}
plugins: [jekyll-feed]
